main: se.etnolit.mchogs.HogsPlugin
name: MC-HOGS
version: 1.0
author: Linus Törngren
description: Plugin for private H.O.G.S. server.
api-version: 1.17
commands:
  cake:
    description: Everybody likes cake
    usage: /cake
    permission: mchogs.cake
permissions:
  mchogs.cake:
    description: Allows you to get cake.
    default: true
